image: node:slim

stages:
  - build

build:
  stage: build
  script:
  - npm install -g static-marks
  - /usr/local/bin/static-marks files/* -o index.html
  artifacts:
    paths:
    - index.html
  only:
  - master
